name: Publish feed.json

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      env:
        TITLE: SF Symbols Viewer
        SUBTITLE: SF Symbols Browser for iPadOS.
        PUBLISHER_NAME: Kenta Kubo
        FEED_IDENTIFIER: xyz.kebo.playgroundbook.SF-Symbols-Viewer
        CONTACT_URL: https://kebo.xyz
        DOCUMENT_TITLE: SF Symbols Viewer
        DOCUMENT_OVERVIEW_SUBTITLE: SF Symbols Browser for iPadOS.
        DOCUMENT_DESCRIPTION: You can browse SF Symbols.
        DOCUMENT_CONTENT_IDENTIFIER: xyz.kebo.playgroundbook.SF-Symbols-Viewer.SF-Symbols-Viewer
        DOCUMENT_URL: https://kebo.xyz/SF-Symbols-Viewer/SF%20Symbols%20Viewer.playgroundbook.zip
        PLAYGROUNDBOOK_FILENAME: SF Symbols Viewer.playgroundbook
      run: |
        zip -r "${PLAYGROUNDBOOK_FILENAME}.zip" "${PLAYGROUNDBOOK_FILENAME}"
        DOCUMENT_SHA512=$(sha512sum "${PLAYGROUNDBOOK_FILENAME}.zip" | awk '{print $1}')
        DOCUMENT_PUBLISHED_DATE=2019-10-11T00:16:00+0900
        DOCUMENT_LAST_UPDATED_DATE=$(date -Iseconds)
        TAG_NAME=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')
        DOCUMENT_CONTENT_VERSION=$(echo $TAG_NAME | cut -c 2-)
        cat > feed.json << EOF
        {
            "title": "${TITLE}",
            "subtitle": "${SUBTITLE}",
            "publisherName": "${PUBLISHER_NAME}",
            "feedIdentifier": "${FEED_IDENTIFIER}",
            "contactURL": "${CONTACT_URL}",
            "formatVersion": "1.2",
            "documents": [
                {
                    "title": "${DOCUMENT_TITLE}",
                    "overviewSubtitle": "${DOCUMENT_OVERVIEW_SUBTITLE}",
                    "description": "${DOCUMENT_DESCRIPTION}",
                    "contentIdentifier": "${DOCUMENT_CONTENT_IDENTIFIER}",
                    "contentVersion": "${DOCUMENT_CONTENT_VERSION}",
                    "url": "${DOCUMENT_URL}",
                    "publishedDate": "${DOCUMENT_PUBLISHED_DATE}",
                    "lastUpdatedDate": "${DOCUMENT_LAST_UPDATED_DATE}",
                    "sha512": "${DOCUMENT_SHA512}",
                    "thumbnailURL": "https://raw.githubusercontent.com/kkk669/SF-Symbols-Viewer/${TAG_NAME}/images/thumbnail.png",
                    "bannerImageURL": "https://raw.githubusercontent.com/kkk669/SF-Symbols-Viewer/${TAG_NAME}/images/banner.png",
                    "previewImageURLs": [
                        "https://raw.githubusercontent.com/kkk669/SF-Symbols-Viewer/${TAG_NAME}/images/preview.png"
                    ],
                    "additionalInformation": [
                        {
                            "name": "Languages",
                            "value": "English"
                        }
                    ]
                }
            ]
        }
        EOF
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: mkdir public && mv SF\ Symbols\ Viewer.playgroundbook.zip feed.json public/
